# Generated by Django 4.2.4 on 2023-10-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sub_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('github_link', models.CharField(max_length=100, null=True)),
                ('documentation_link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
